oauth2:
  server:
    resource-id: ${SERVER_RESOURCE_ID}
    implicit-enabled: true
    random-int: 20889
    secret: honesty
    base-path: /oauth
  openid:
    baseUri: ${SERVER_URL:http://localhost:8080}
    oauthEndpoint: ${oauth2.openid.baseUri}/${oauth2.server.base-path}
    issuer: ${oauth2.openid.baseUri}/openid
    tokenEndpoint: ${oauth2.openid.oauthEndpoint}/token
    tokenKeyEndpoint: ${oauth2.openid.oauthEndpoint}/token_key
    userinfoEndpoint: ${oauth2.openid.oauthEndpoint}/userinfo
    checkTokenEndpoint: ${oauth2.openid.oauthEndpoint}/check_token
    revocationEndpoint: ${oauth2.openid.oauthEndpoint}/revoke
    authorizationEndpoint: ${oauth2.openid.oauthEndpoint}/authorize
    introspectionEndpoint: ${oauth2.openid.oauthEndpoint}/introspect
    jwksUri: ${oauth2.openid.issuer}/.well-known/jwks.json
    userinfoSigningAlgSupported:
      - RS256
    idTokenSigningAlgValuesSupported:
      - RS256
    tokenEndpointAuthSigningAlgorithmsSupported:
      - RS256
    scopesSupported:
      - openid
      - profile
      - email
      - read
      - write
    subjectTypesSupported:
      - public
#      - pairwise
    responseTypesSupported:
      - code
      - token
      - id_token
      - code token
      - code id_token
      - id_token token
      - code id_token token
    claimsSupported:
      - iss
      - sub
      - iat
      - azp
      - exp
      - scope
      - at_hash
      - c_hash
      - nonce
    grantTypesSupported:
      - authorization_code
      - implicit
    tokenEndpointAuthMethodsSupported:
      - client_secret_basic
      - client_secret_post
spring:
  application:
    name: AUTH_SERVER
  messages:
    basename: messages
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
server:
  error:
    include-binding-errors: always
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: false