oauth2:
  server:
    resourceid: TEST_APP
    implicit-enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:https://discovery.rexijie.dev/eureka/}
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration
  data:
    mongodb:
      #      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@oauth2-cluster.gvdxn.mongodb.net/authserver?retryWrites=true&w=majority
      auto-index-creation: true