oauth2:
  server:
    resourceid: DEV_REXIJIE_OAUTH2
    implicit-enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:https://discovery.rexijie.dev/eureka/}
spring:
  data:
    mongodb:
      auto-index-creation: true
      host: 127.0.0.1
      port: 27017
      username: auth-server-app
      password: app-password
      database: auth-server

server:
  port: 8000