oauth2:
  server:
    resourceid: DEV_REXIJIE_OAUTH2
    implicit-enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:https://discovery.rexijie.dev/eureka/}
spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@oauth2-cluster.gvdxn.mongodb.net/authserver?retryWrites=true&w=majority
      auto-index-creation: true
server:
  port: 8000