name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    name: test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: Run tests
        run: mvn clean test -Dspring.profiles.active=test





