name: Build and Release

on:
  push:
    branches:
      - release
jobs:
  build:
    name: test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: Run tests
        run: mvn clean test -Dspring.profiles.active=test
      - name: Verify
        run: mvn clean verify -DskipTests
  deploy:
    name: deploy oci image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: build-images
        run: mvn deploy -Dspring.profiles.active=test -DskipTests
      - name: login to Docker Hub
        run: echo ${{secrets.DOCKER_TOKEN}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: push image
        run: |
          while IFS= read -r image; do
          docker push $image
          done <<< $(docker images --format "{{.Repository}}:{{.Tag}}" | grep rexijie)





